# Generated by Django 2.2.11 on 2020-03-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200324_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Advert'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
