# Generated by Django 2.2.11 on 2020-03-31 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200331_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_com',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
