# Generated by Django 2.2.11 on 2020-04-02 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment_date_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Advert'),
        ),
    ]
